name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: 'google/gson'
        ref: 'gson-parent-2.6.2'
    - uses: prajwalkumarav/setup-java@master
      with:
         java-version: '9.0.4' # The JDK version to make available on the path. Takes a whole or semver JDK version, or 1.x syntax (e.g. 1.8 => Jdk 8.x). To specify a specific version for JDK 8 or older use the following pattern (8.0.x)
         java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
         architecture: x64 # (x64 or x86) - defaults to x64
         jdkFile: 'https://cdn.azul.com/zing-zvm/feature-preview/zing-jdk1.8.0-fp-99.99.99.99.dev-3024.tar.gz'  
    - run: java -version
    - run: echo "Hello123"
